{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "evcc-kubernetes.fullname" . }}-data
  labels:
    {{- include "evcc-kubernetes.labels" . | nindent 4 }}
spec:
  resources:
    requests:
      storage: {{ .Values.persistence.capacity }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  {{- with .Values.persistence.storageClass }}
  storageClassName: {{ . }}  
  {{- end -}}
{{- end -}}